title = "Thulite"
baseurl = "http://localhost/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
pagerSize = 10
rssLimit = 10
summarylength = 20 # 70 (default)

# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["de", "nl"]
defaultContentLanguageInSubdir = false

copyRight = "Copyright (c) 2010-2024 Ventizo"

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS", "searchIndex"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = -1 # "30m"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  type = "types"
  technology = "technologies"
  pricing = "pricing"
  sort = "sorts"

[permalinks]
  blog = "/blog/:title/"
  themes = "/themes/:title/"
  types = "/themes/:title/"
  technologies = "/technologies/:title/"
  pricing = "/pricing/:title/"
  sorts = "/integrations/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "types"
    weight = 100
    [[related.indices]]
    name = "technologies"
    weight = 80
    [[related.indices]]
    name = "pricing"
    weight = 10
    # [[related.indices]]
    # name = "categories"
    # weight = 100
    # [[related.indices]]
    # name = "tags"
    # weight = 80
    # [[related.indices]]
    # name = "date"
    # weight = 10

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"
