[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  HUGO_VERSION = "0.129.0"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
  from = "https://gethyas.com/*"
  to = "https://thulite.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gethyas.com/*"
  to = "https://thulite.io/"
  status = 301
  force = true

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self' https://plausible.io/api/event https://ingesteer.services-prod.nsvcs.net https://bam.eu01.nr-data.net/1/NRJS-0d3677f69b20019eb53; font-src 'self'; img-src 'self' https://avatars.githubusercontent.com data:; script-src 'self' https://plausible.io/js/script.js https://netlify-rum.netlify.app https://ingesteer.services-prod.nsvcs.net https://js-agent.newrelic.com 'nonce-dXNlcj0iaGVsbG8iLGRvbWFpbj0iaGVua3ZlcmxpbmRlLmNvbSIsZG9jdW1lbnQud3JpdGUodXNlcisiQCIrZG9tYWluKTs=' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk=' 'sha256-De+H72F5hpOAzW2zAiPblIe9+YnIOY7IFW02262CIcs='; style-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Feature-Policy = "geolocation 'self'"
    Cache-Control= '''
    public,
    max-age=31536000'''
    Access-Control-Allow-Origin = "*"
